### ISSUE TITLE
handle_move_result runs on opponent's clock in local games

### ISSUE THREAD

**Issue by ginop** [reconnaissanceblindchess/reconchess#14]
The function play_move in play.py calls game.end_turn before player.handle_move_result. This causes play_local_game to run handle_move_result while the clock counts against the current player's opponent.

This order is important for play_remote_game, since the opponent can begin the next turn while the current player runs handle_move_result. In this case the clock functions as intended.

I do not see an obvious fix for play_local_game that does not interfere with play_remote_game.

**Comment by coreylowman** [comment]
Thanks for reporting this, we'll be fixing this in the next version. We are adding a flag to `play_turn` and `play_move` that dictates when `end_turn` is called. For local games `end_turn` will be called last, and for remote games the behavior stays the same.

Its unfortunate that timings are a bit different between remote and local games, but on the positive side you will usually use less time in remote games.

**Comment by coreylowman** [comment]
This was resolved in 63c9ce8c256ad5f0866cf9b620e561da9f30ecd2
