### ISSUE TITLE
How do you exit ranked mode?

### ISSUE THREAD

**Issue by ginop** [reconnaissanceblindchess/reconchess#17]
Does ranked mode provide a mechanism for disconnecting a bot? (Other than simply shutting down the bot and losing any in-progress games)

We could set up our bot to stop posting the accept_invitation method's message, but it isn't clear how the server would handle games that were scheduled but not acknowledged. How are those recorded?

Looking forward to participating in ranked mode once we have this aspect figured out!

Thanks.

**Comment by coreylowman** [comment]
Thanks for bringing this up. Currently rc-connect does not handle this.

We will work on some changes to rc-connect to make this possible. It will likely involve a post to the server to turn ranked mode off on a ctrl+c and then waiting for the existing games to finish.

**Comment by coreylowman** [comment]
We've identified a fix to this and are working on testing on multiple platforms and running configurations.

**Comment by coreylowman** [comment]
Fix pushed here: https://github.com/reconnaissanceblindchess/reconchess/commit/9bbc1dc42eecec9a2acc9b5d4a055b76b219e086

Docs here: https://reconchess.readthedocs.io/en/latest/ranked.html#disconnecting-your-bot

Resolution is rc-connect now listens for interrupt/terminate signals, sends message to server telling it to not schedule anymore ranked games, and then waits for any in progress games to finish before exiting.
