### ISSUE TITLE
Information leak in /move_actions related to en passant capture

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [reconnaissanceblindchess/reconchess#18]
Iff the opponent just made a pawn double push that enables en passant capture, `/move_actions` will list corresponding capture twice.

This is probably caused by not clearing en passant square in the `without_opponent_pieces()` function.

**Comment by coreylowman** [comment]
Hey Vlad, thanks for reporting this. You're correct about the cause, we've added a new unit test and fix for this. Will be pushing soon.

**Comment by coreylowman** [comment]
Resolved in 1d752a89113ca07bd3cfa5544f20833b46b3b79e
