### ISSUE TITLE
stockfish executable issue with windows 

### ISSUE THREAD

**Issue by garretvo19** [reconnaissanceblindchess/reconchess#21]
Hi,

 I am wondering whether someone can help me resolve the stockfish executable variable with windows. I downloaded stockfish engine for windows. The path to the executable file in my folder is: 'C:\Users\ga\stockfish_13_win_x64_bmi2'.  Therefore, the executable path is: ''C:\Users\ga\stockfish_13_win_x64_bmi2\stockfish_13_win_x64_bmi2.exe'. I tried this path to execute the stockfish engine, and it failed. Can you please give me some pointers ?

**Comment by ginop** [comment]
Happy to try to help! You didn't say what the error was or what you were trying to do specifically, though, so I can only guess for now.

In general, the neural network versions of Stockfish (12 or higher) can get themselves into positions that crash the engine. This doesn't happen in regular chess, but reconchess can create board states that aren't possible traditionally. Try with Stockfish 11 and see if that resolves it.

**Comment by ginop** [comment]
I'm closing this issue, but if you have further questions feel free to ask them here. (If you do, include some more detail about the errors you see!)

**Comment by garretvo19** [comment]
Hi,
Sorry for the late response. I was quite busy this week. I tried with the stockfish 11. I put the executable path into my code as follows:

STOCKFISH_ENV_VAR = 'C:\\Users\\ga\\stockfish-11-win\\Windows' 
I run my code, and I still get the same error. The error is as follows:
Traceback (most recent call last):
  File "c:\users\ga\anaconda3\lib\site-packages\reconchess\scripts\rc_bot_match.py", line 22, in main
    winner_color, win_reason, history = play_local_game(white_player_cls(), black_player_cls(), game=game)
  File "C:\Users\ga\Dropbox\gtd\trout_bot.py", line 17, in __init__
    raise KeyError('required environment variable called "{}" pointing to the stockfish executable'.format(STOCKFISH_ENV_VAR))
KeyError: 'required environment variable called "C:\\Users\\ga\\stockfish-11-win\\Windows" pointing to the stockfish executable'
Game Over!
Winner: ERROR!
Saving replay to RandomBot-TroutBot-ERROR-2021_06_24-21_12_42.json...

If you can give me some hints, I would appreciate it.

**Comment by ginop** [comment]
Ah, okay, there are a couple more changes to make that will help!

The environment variable needs to point to the engine itself, not just the directory it is in. Something like `'C:\Users\ga\stockfish-11-win\Windows\stockfish_20011801_x64.exe'`

Also, it looks like you've mixed up a little of what is going on in that code. The Python code for trout_bot has a variable near the top which is `STOCKFISH_ENV_VAR = 'STOCKFISH_EXECUTABLE'`. Leave that alone; it just tells Python that the name of the environment variable that says where Stockfish is has the name STOCKFISH_EXECUTABLE. In fact, you don't change the Python code at all for this, you need to create an environment variable outside of Python that points to the engine. On Windows, run the command `set STOCKFISH_EXECUTABLE = 'C:\Users\ga\stockfish-11-win\Windows\stockfish_20011801_x64.exe'` before running reconchess code that needs that variable, or type 'environment' in the start menu to set this variable in a GUI.

**Comment by garretvo19** [comment]
Thank you for your answer. I appreciate it
