### ISSUE TITLE
Add more baseline bots

### ISSUE THREAD

**Issue by acxz** [reconnaissanceblindchess/reconchess#24]
In addition to the trout_bot, would it be possible to add the baseline bots, Oracle and Marmot mentioned on the [challenge webpage](https://rbc.jhuapl.edu/challenge)?

**Comment by ginoperrotta** [comment]
You can challenge any connected bot (that isn't already busy with too many games)! Occasionally, the servers get restarted, and the usual baseline bots remain offline for a while.

**Comment by acxz** [comment]
I'm sorry that I wasn't clear, I was referring to adding the code for the baseline bots to this repo under `/reconchess/bots` like how to code exists for trout. This allows for users to play against these bots locally.

I understand that the code for bots like Strangefish2 and others would be closed source, but would it be possible to share the code for the baseline bots?

**Comment by ginoperrotta** [comment]
Oh, I see! Yes, several bots authored by APL employees are under review for public release. It is a slow process, but eventually Oracle and StrangeFish2 will be available. These will not be included in the reconchess library, but will be accessible from their own repos.

**Comment by acxz** [comment]
I see thanks for that! What about Marmot?

I assume the individual repos for the released bots will be linked somehow from the webpage?
