### ISSUE TITLE
feature engineering

### ISSUE THREAD

**Issue by daihuiao** [reconnaissanceblindchess/reconchess#25]
it is highly recommended to organized the code in the way of openai-gym, feature engineering waste me lot of time

**Comment by ginoperrotta** [comment]
Discussed a bit more here https://github.com/reconnaissanceblindchess/reconchess/issues/23#issuecomment-1108567061

In short, complex games do not fit in the openai-gym environment API.

**Comment by daihuiao** [comment]
thank you for your reply
